version: 2.1

jobs:
  build:
    docker:
    - image: vault:1.3.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          ./src/scripts/install-dependencies.sh
          make docker-build-and-push
