version: 2.1

jobs:
  init:
    docker:
      - image: opuscapita/minsk-core-machineuser-env:2
    steps:
      - run: circle_ci_add_env.sh
  build:
    docker:
    - image: vault:1.3.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          ./src/scripts/install-dependencies.sh
          make docker-build-and-push
workflows:
  version: 2
  commit:
    jobs:
      - init
      - build:
          requires:
            - init
